{
 "title": "Call Center - Opa Suite",
 "tags": [
  "call center",
  "opa suite",
  "whatsapp",
  "messenger",
  "pabx",
  "atendimentos"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SERVIDOR",
    "query": {}
   },
   {
    "name": "CANAL",
    "query": {}
   },
   {
    "name": "ATENDENTE",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Aguardando Atendimento - $CANAL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": {
      "filter": "Aguardando Atendimento por Canais"
     },
     "functions": [
      {
       "$$hashKey": "object:109",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Aguardando Atendimento Canal (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Aguardando Atendimento Canal (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": {
      "filter": "Aguardando Atendimento Canal $CANAL"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Em Atendimento - $CANAL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Em Atendimento por Canais" },
     "functions": [
      {
       "$$hashKey": "object:59",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Em Atendimento Canal (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Em Atendimento Canal (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "Em Atendimento Canal $CANAL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Em Atendimetnto",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "application": {
      "filter": "Contador de Atendimento por Usuario"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Usuario (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Usuario (.*)/, $1)",
       "$$hashKey": "object:167"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "Usuario $ATENDENTE" },
     "itemTag": {
      "filter": "Application: Contador de Atendimento por Usuario"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 7 },
   "options": {
    "content": "<center>\n    <p style=\"font-size:37px; background-color:#00FF7F;color:black\">\n        Aguardando Atendimento\n    </p>\n</center>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 7 },
   "options": {
    "content": "<br>\r\n<br>\r\n<center>\r\n    <img src=\"https://conectsantarem.com.br/mac/img/logo.png\"\r\n    width=\"\"\r\n    height=\"\">\r\n</center>"
   },
   "targets": [
    {
     "application": { "filter": "OPA - Usuarios" },
     "functions": [
      {
       "$$hashKey": "object:140",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Usuarios (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Usuarios (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "Opa Suite" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 7 },
   "options": {
    "content": "<center>\n<p style=\"font-size:37px; background-color:#00FF7F;color:black\">\nEm Atendimento\n</p>    \n</center>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CANAIS DE ATENDIMENTO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "Aguardando Atendimento por Canais"
     },
     "functions": [
      {
       "$$hashKey": "object:32",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Aguardando Atendimento Canal (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Aguardando Atendimento Canal (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CANAIS DE ATENDIMENTO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Em Atendimento por Canais" },
     "functions": [
      {
       "$$hashKey": "object:59",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Em Atendimento Canal (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Em Atendimento Canal (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 11 },
   "options": {
    "content": "<center>\r\n    <img src=\"https://conectchat.com.br/atendente/login/images/opasuite.svg\"\r\n    width=\"200 \">\r\n</center>"
   },
   "targets": [
    {
     "application": { "filter": "OPA - Usuarios" },
     "functions": [
      {
       "$$hashKey": "object:140",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Usuarios (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Usuarios (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "Opa Suite" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SETOR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "Aguardando Atendimento por Setor"
     },
     "functions": [
      {
       "$$hashKey": "object:86",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Aguardando Atendimento Setor (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Aguardando Atendimento Setor (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SETOR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Em Atendimento por Setor" },
     "functions": [
      {
       "$$hashKey": "object:167",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Em Atendimento Setor (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Em Atendimento Setor (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "USUARIOS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Usuarios" },
     "functions": [
      {
       "$$hashKey": "object:140",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Total de Usuários (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Total de Usuários (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Saldo SMS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Saldo" },
     "functions": [
      {
       "$$hashKey": "object:111",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "$1 - "
       ],
       "text": "replaceAlias(/(.*)/, $1 - )"
      }
     ],
     "group": { "filter": "Hotmobile" },
     "host": { "filter": "Hotmobile SMS" },
     "item": { "filter": "Saldo SMS" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Em atendimento por Atendente",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Contador de Atendimento por Usuario"
     },
     "functions": [
      {
       "$$hashKey": "object:167",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Usuario (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Usuario (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Em atendimento por Setor",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Em Atendimento por Setor" },
     "functions": [
      {
       "$$hashKey": "object:194",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Em Atendimento Setor (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Em Atendimento Setor (.*)/, $1)"
      }
     ],
     "group": { "filter": "OPA SUITE" },
     "host": { "filter": "$SERVIDOR" },
     "item": { "filter": "/Em Atendimento Setor/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}